# Generated by Django 3.2.9 on 2021-11-30 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_cart_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_progress', 'Order in progress'), ('is_ready', 'Order ready'), ('completed', 'Order completed')], default='new', max_length=100, verbose_name='Order Status')),
                ('buying_type', models.CharField(choices=[('self', 'Self-pickup'), ('delivery', 'Delivery')], default='self', max_length=100, verbose_name='Order Type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment for order')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date of order creation')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of order receipt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Buyer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='mainapp.Order', verbose_name='Customer orders'),
        ),
    ]
