# Generated by Django 3.2.9 on 2021-11-30 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date of order receipt'),
        ),
    ]
